/// Roman-Urdu + brand-generic grocery vocabulary (Saad, 2026-07-11):
/// Pakistani users type
/// "doodh", "cheeni", "sawaiyan" in English letters. Each alias maps
/// spelling variants to canonical seed-catalog entries so autocomplete and
/// auto-categorization understand them. The user's own word stays as the
/// item's display name — the alias only finds the right catalog row.
///
/// Keys are normalized (lowercase, trimmed). Values are seed-catalog
/// `nameNormalized` targets; ambiguous words (gosht, daal, tel) fan out to
/// several. Integrity is enforced by test: every target must exist in
/// kSeedCatalog.
library;

const Map<String, List<String>> kUrduAliases = {
  // Dairy & Eggs
  'doodh': ['milk'], 'dudh': ['milk'], 'dood': ['milk'],
  'dhoodh': ['milk'], 'doodh ka packet': ['milk'],
  'dahi': ['yogurt'], 'dahee': ['yogurt'], 'dahi ka dabba': ['yogurt'],
  'anday': ['eggs'], 'anda': ['eggs'], 'ande': ['eggs'], 'andey': ['eggs'],
  'andaa': ['eggs'], 'undey': ['eggs'],
  'makhan': ['butter'], 'makkhan': ['butter'], 'mukhan': ['butter'],
  'malai': ['cream'], 'balai': ['cream'],
  'ghee': ['desi ghee'],
  'banaspati': ['banaspati ghee'], 'dalda': ['banaspati ghee'],
  'vanaspati': ['banaspati ghee'],
  'khoya': ['cream'],
  'doodh powder': ['milk powder'], 'khushk doodh': ['milk powder'],

  // Staples
  'chawal': ['basmati rice'], 'chaawal': ['basmati rice'],
  'chawel': ['basmati rice'], 'chaval': ['basmati rice'],
  'chawl': ['basmati rice'], 'sella chawal': ['basmati rice'],
  'basmati': ['basmati rice'], 'rice': ['basmati rice'],
  'aata': ['atta'], 'ata': ['atta'], 'gandum ka atta': ['atta'],
  'kanak': ['atta'], 'chakki atta': ['atta'],
  'meda': ['maida'],
  'basan': ['besan'],
  'soojee': ['sooji'],
  'daliya': ['dalia'],
  'jai': ['oats'], 'jaee': ['oats'],
  'makai ka atta': ['cornflour'],
  'noodle': ['noodles'],
  'cheeni': ['sugar'], 'chini': ['sugar'], 'khaand': ['sugar'],
  'khand': ['sugar'], 'cheene': ['sugar'],
  'shakkar': ['brown sugar'], 'shakar': ['brown sugar'],
  'namak': ['salt'], 'nimak': ['salt'],
  'dal': ['daal chana', 'daal masoor', 'daal moong', 'daal mash'],
  'daal': ['daal chana', 'daal masoor', 'daal moong', 'daal mash'],
  // Reversed word order — people type "chana daal", the seed says
  // "daal chana", and LIKE can't flip words.
  'chana daal': ['daal chana'], 'chana dal': ['daal chana'],
  'masoor daal': ['daal masoor'], 'masoor dal': ['daal masoor'],
  'moong daal': ['daal moong'], 'moong dal': ['daal moong'],
  'mash daal': ['daal mash'], 'mash dal': ['daal mash'],
  'mash ki daal': ['daal mash'], 'urad daal': ['daal mash'],
  'urad dal': ['daal mash'], 'kali daal': ['daal mash'],
  'chanay ki daal': ['daal chana'], 'daal chanay': ['daal chana'],
  'baisan': ['besan'],
  'suji': ['sooji'], 'sujee': ['sooji'],
  'sawaiyan': ['vermicelli'], 'sewaiyan': ['vermicelli'],
  'seviyan': ['vermicelli'], 'sawayyan': ['vermicelli'],
  'sewiyan': ['vermicelli'],
  'chane': ['white chickpeas'], 'chanay': ['white chickpeas'],
  'kabuli chanay': ['white chickpeas'],
  'lobia': ['red beans'], 'rajma': ['red beans'],

  // Vegetables
  'aloo': ['potatoes'], 'alu': ['potatoes'], 'aalu': ['potatoes'],
  'aaloo': ['potatoes'], 'alloo': ['potatoes'],
  'pyaz': ['onions'], 'piyaz': ['onions'], 'pyaaz': ['onions'],
  'piaz': ['onions'], 'payaz': ['onions'],
  'tamatar': ['tomatoes'], 'timatar': ['tomatoes'],
  'tamater': ['tomatoes'], 'timater': ['tomatoes'],
  'adrak': ['ginger'], 'adrak lehsun': ['ginger', 'garlic'],
  'lehsun': ['garlic'], 'lahsun': ['garlic'], 'lasan': ['garlic'],
  'lehsan': ['garlic'], 'lassan': ['garlic'], 'thoom': ['garlic'],
  'hari mirch': ['green chillies'], 'mirchi': ['green chillies'],
  'hari mirchain': ['green chillies'], 'mirchain': ['green chillies'],
  'sabz mirch': ['green chillies'],
  'dhania': ['coriander'], 'dhaniya': ['coriander'],
  'hara dhania': ['coriander'], 'dhanya': ['coriander'],
  'podina': ['mint'], 'pudina': ['mint'], 'pudeena': ['mint'],
  'podeena': ['mint'],
  'palak': ['spinach'],
  'bhindi': ['okra'],
  'gobi': ['cauliflower'], 'phool gobi': ['cauliflower'],
  'phul gobi': ['cauliflower'], 'gobhi': ['cauliflower'],
  'phool gobhi': ['cauliflower'],
  'band gobi': ['cabbage'], 'bund gobi': ['cabbage'],
  'band gobhi': ['cabbage'], 'patta gobi': ['cabbage'],
  'gajar': ['carrots'], 'gaajar': ['carrots'], 'gajjar': ['carrots'],
  'matar': ['peas'], 'mattar': ['peas'], 'muttar': ['peas'],
  'kheera': ['cucumber'], 'khira': ['cucumber'], 'kheeray': ['cucumber'],
  'shimla mirch': ['capsicum'], 'shimla': ['capsicum'],
  'baingan': ['brinjal'], 'bengan': ['brinjal'], 'baigan': ['brinjal'],
  'baingun': ['brinjal'],
  'karela': ['bitter gourd'], 'karelay': ['bitter gourd'],
  'karele': ['bitter gourd'],
  'kaddu': ['pumpkin'], 'kadu': ['pumpkin'],
  'mooli': ['radish'], 'muli': ['radish'],
  'shaljam': ['turnip'], 'shalgam': ['turnip'],
  'chukandar': ['beetroot'], 'chuqandar': ['beetroot'],
  // Urdu-primary rows, reachable from English too.
  'bottle gourd': ['lauki'], 'ghia': ['lauki'], 'kaddu gol': ['lauki'],
  'loki': ['lauki'], 'louki': ['lauki'],
  'ridge gourd': ['tori'], 'turai': ['tori'], 'torai': ['tori'],
  'taro': ['arvi'], 'arbi': ['arvi'], 'arwi': ['arvi'],
  'fenugreek': ['methi'],
  'sweet potato': ['shakarkandi'], 'shakar kandi': ['shakarkandi'],
  'corn': ['makai'], 'bhutta': ['makai'], 'sweet corn': ['makai'],
  'makkai': ['makai'], 'challi': ['makai'], 'chhalli': ['makai'],
  'salad patta': ['lettuce'], 'salad': ['lettuce'],
  'sag': ['saag'], 'sarson ka saag': ['saag'],

  // Fruit
  'aam': ['mangoes'], 'amb': ['mangoes'],
  'kela': ['bananas'], 'kelay': ['bananas'], 'kele': ['bananas'],
  'kaila': ['bananas'], 'kailay': ['bananas'],
  'santra': ['oranges'], 'sangtra': ['oranges'], 'malta': ['oranges'],
  'kinnow': ['oranges'], 'kino': ['oranges'], 'kinu': ['oranges'],
  'santara': ['oranges'], 'sangtara': ['oranges'],
  'angoor': ['grapes'], 'angur': ['grapes'], 'angoors': ['grapes'],
  'anar': ['pomegranate'], 'anaar': ['pomegranate'],
  'khajoor': ['dates'], 'khajur': ['dates'], 'chuhara': ['dates'],
  'khajooren': ['dates'],
  'seb': ['apples'], 'saib': ['apples'], 'sev': ['apples'],
  'nimbu': ['lemons'], 'limu': ['lemons'], 'leemu': ['lemons'],
  'limoo': ['lemons'], 'lemo': ['lemons'],
  'guava': ['amrood'], 'amrud': ['amrood'],
  'watermelon': ['tarbooz'], 'tarbuz': ['tarbooz'],
  'melon': ['kharbooza'], 'garma': ['kharbooza'],
  'kharbuza': ['kharbooza'],
  'pear': ['nashpati'], 'naspati': ['nashpati'],
  'papaya': ['papita'],
  'strawberry': ['strawberries'],
  'cheeku': ['chikoo'], 'chiku': ['chikoo'],

  // Meat & Fish
  'murghi': ['chicken'], 'murgi': ['chicken'], 'murgh': ['chicken'],
  'broiler': ['chicken'], 'desi murghi': ['chicken'],
  'murghi ka gosht': ['chicken'], 'chicken gosht': ['chicken'],
  'gosht': ['beef', 'mutton'], 'ghosht': ['beef', 'mutton'],
  'bara gosht': ['beef'], 'chota gosht': ['mutton'],
  'bakray ka gosht': ['mutton'], 'bakra': ['mutton'],
  'gaye ka gosht': ['beef'],
  'keema': ['qeema'], 'kima': ['qeema'], 'qima': ['qeema'],
  'qeemah': ['qeema'], 'keyma': ['qeema'],
  'machli': ['fish'], 'machhli': ['fish'], 'machlee': ['fish'],
  'machi': ['fish'],
  'jhinga': ['prawns'], 'jheenga': ['prawns'], 'jhingay': ['prawns'],
  'kalejee': ['kaleji'], 'kalayji': ['kaleji'], 'liver': ['kaleji'],

  // Spices & Condiments
  'haldi': ['turmeric powder'], 'huldi': ['turmeric powder'],
  'lal mirch': ['red chilli powder'], 'surkh mirch': ['red chilli powder'],
  'pisi mirch': ['red chilli powder'], 'kuti mirch': ['red chilli powder'],
  'pisi lal mirch': ['red chilli powder'],
  'zeera': ['cumin'], 'jeera': ['cumin'], 'zira': ['cumin'],
  'zeerah': ['cumin'], 'safed zeera': ['cumin'],
  'kali mirch': ['black pepper'], 'kaali mirch': ['black pepper'],
  'elaichi': ['cardamom'], 'ilaichi': ['cardamom'],
  'elachi': ['cardamom'], 'ilachi': ['cardamom'],
  'darchini': ['cinnamon'], 'dalchini': ['cinnamon'],
  'dar cheeni': ['cinnamon'],
  'laung': ['cloves'], 'loung': ['cloves'], 'long': ['cloves'],
  'tez patta': ['bay leaves'], 'tej patta': ['bay leaves'],
  'imli': ['tamarind'], 'imlee': ['tamarind'],
  'sirka': ['vinegar'], 'sirkah': ['vinegar'],
  'garm masala': ['garam masala'],
  'chat masala': ['chaat masala'],
  'sabut dhania': ['coriander powder'],
  'ajwaain': ['ajwain'],
  'kalongi': ['kalonji'], 'kalwanji': ['kalonji'],
  'zaitoon ka tel': ['olive oil'], 'zaitoon': ['olive oil'],
  'shehad': ['honey'], 'shehed': ['honey'], 'shahad': ['honey'],
  'gurr': ['gur'],
  'badam': ['almonds'],
  'kaju': ['cashews'],
  'kishmish': ['raisins'],
  'moongphali': ['peanuts'], 'mumphali': ['peanuts'],
  'moong phali': ['peanuts'],
  'akhrot': ['walnuts'],
  'pista': ['pistachios'],
  'sonf': ['saunf'],
  'tel': ['cooking oil'], 'sarson ka tel': ['cooking oil'],
  'khana pakane ka tel': ['cooking oil'],

  // Beverages
  'chai': ['tea'], 'chai patti': ['tea'], 'chaey': ['tea'],
  'chae': ['tea'], 'patti': ['tea'], 'chai ki patti': ['tea'],
  'chaye': ['tea'], 'cha': ['tea'],
  'kafi': ['coffee'], 'kaafi': ['coffee'],
  'pani': ['mineral water'], 'paani': ['mineral water'],
  'pani ki botal': ['mineral water'],
  'sharbat': ['squash'],
  'cold drink': ['soft drink'], 'colddrink': ['soft drink'],
  'botal': ['soft drink'],
  'roohafza': ['rooh afza'],

  // Bakery
  'double roti': ['bread'], 'dubble roti': ['bread'],
  'dabal roti': ['bread'],
  'kulcha': ['naan'], 'kulchay': ['naan'], 'nan': ['naan'],
  'bun': ['buns'],
  'papay': ['rusk'], 'paapay': ['rusk'],
  'biscuit': ['biscuits'], 'bisket': ['biscuits'],
  'biskut': ['biscuits'],
  'chaklet': ['chocolate'],
  'papad': ['papar'],

  // Frozen
  'samosa': ['frozen samosa'], 'samosay': ['frozen samosa'],
  'samosas': ['frozen samosa'], 'samose': ['frozen samosa'],
  'paratha': ['frozen paratha'], 'parathay': ['frozen paratha'],
  'parathe': ['frozen paratha'],
  'kabab': ['frozen kebab'], 'kebab': ['frozen kebab'],
  'kababs': ['frozen kebab'], 'shami kabab': ['frozen kebab'],
  'kabaab': ['frozen kebab'],
  'nuggets': ['chicken nuggets'],
  'fries': ['french fries'], 'finger chips': ['french fries'],

  // Household & personal
  'sabun': ['soap bars'], 'saban': ['soap bars'],
  'sabun ki tikki': ['soap bars'], 'nahanay wala sabun': ['soap bars'],
  'surf': ['laundry detergent'], 'washing powder': ['laundry detergent'],
  'kapray dhonay wala surf': ['laundry detergent'],
  'machis': ['matchbox'], 'machiss': ['matchbox'],
  'maachis': ['matchbox'],
  'machar spray': ['mosquito repellent'],
  'machar wala spray': ['mosquito repellent'],
  'mortein': ['mosquito repellent'],
  'broom': ['jharoo'], 'jhadu': ['jharoo'], 'jharu': ['jharoo'],
  'pocha': ['mop'],
  'phenyl': ['floor cleaner'], 'fenyl': ['floor cleaner'],
  'harpic': ['toilet cleaner'],
  'vim': ['dishwashing liquid'],
  'bulb': ['light bulb'],
  'battery': ['batteries'], 'cell': ['batteries'],
  'tissue': ['tissues'], 'tissue paper': ['tissues'],
  'dettol': ['antiseptic liquid'],
  'shempo': ['shampoo'], 'shampu': ['shampoo'],
  'colgate': ['toothpaste'], 'manjan': ['toothpaste'],
  'brush': ['toothbrush'], 'danton ka brush': ['toothbrush'],
  'kanghi': ['comb'], 'kangi': ['comb'],
  'balon ka tel': ['hair oil'],
  'pads': ['sanitary pads'],
  'pampers': ['diapers'], 'diaper': ['diapers'],
  'panadol': ['paracetamol'],
  'sanitizer': ['hand sanitizer'],
};

/// Canonical seed names for a normalized word; empty when unknown.
List<String> canonicalsFor(String normalized) =>
    kUrduAliases[normalized] ?? const [];

/// Canonicals for any alias the typed [prefix] could be starting — this is
/// what lets "sawai" already suggest Vermicelli. Two characters minimum so
/// single letters don't drag in half the map.
Set<String> aliasCanonicalsForPrefix(String prefix) {
  if (prefix.length < 2) return const {};
  return {
    for (final entry in kUrduAliases.entries)
      if (entry.key.startsWith(prefix)) ...entry.value,
  };
}
